검색 API 작성 (#15)
Challenge02/HangehaeMusicClub-BE pull request #26
Opened 2023-01-11 07:06 UTC by yejin0718

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] PR 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정
- [x] PR에는 Projects 탭을 지정하지 않습니다.
- [x] 연결 이슈 close를 작성했는지 확인해주세요!

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
검색API 작성

## 작업사항
- repository 작성
- service 작성
- dto 작성
- controller 작성

## 변경로직
- 내용을 적어주세요.

## 연결 이슈 close

close #15 

## 스크린샷
API 작업 결과(포스트맨, 크롬 등) 스크린샷을 첨부해주세요.

## 기타사항
기타사항을 작성해주세요.

2023-01-11 07:27 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +public class LyricDto {
ResponseLyric Dto가 List형이던데, 해당 Dto 이름을 ResponseLyric으로 해야하지 않나요?

2023-01-11 07:29 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    }
@Builder class단에 사용하면 안되나요?

2023-01-11 07:30 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +public class ResponseLyric {
List형인데 Dto 이름에 List 가 들어가야되지 않나요? 나중에 단건 요청하면 해당 Dto 이름이 맞을 것 같다는 생각입니다.

2023-01-11 07:31 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/dto/ResponseSong.java
> +public class ResponseSong {
음악, 가사 리스트형 dto는 이름에 List가 있어야 되지 않나 생각합니다.

2023-01-11 07:33 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/dto/SongDto.java
> +public class SongDto {
마찬가지로 ResponseSong 이름이 맞지 않나 생각합니다.

2023-01-11 07:34 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	List<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like);
Like %검색어% 를 구현하는데 @Query가 필요한가요?

2023-01-11 07:36 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/response/DataResponse.java
> +public class DataResponse {
CommonResponse Dto가 있는데 별도로 만들어야 하나요?

2023-01-11 07:39 UTC, 1Tsw0rd commented on src/main/java/com/hanghaemusic/response/ResponseSearchList.java
> +public class ResponseSearchList {
response 패키지 안에 있어야 되나요? 다른 곳에서 공용으로 사용되는 DTO는 아니라고 생각합니다.

2023-01-11 07:41 UTC, yanJuicy requested changes

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	List<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like);
왜 Query가 같은 메소드를 2개 만드신 이유가 뭔가요?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	Slice<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like, Pageable pageable);
메소드명에 오타가 있는거 같습니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +public class LyricDto {
Dto 네이밍 컨벤션과 맞지 않습니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +package com.hanghaemusic.dto;
dto라는 패키지는 컨벤셔에 없습니다

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +package com.hanghaemusic.dto;
controller 하위에 reqeust, response 패키지로 dto 패키지를 대신합니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +public class LyricDto {
Dto의 이름이 명확하지 않습니다.
Dto의 이름을 봤을 때 어떤 역할을 하는지 알 수 없습니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +public class ResponseLyric {
LyricResponse의 순서가 컨벤션입니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +import com.hanghaemusic.dto.*;
컨벤션은 싱글 임포트 입니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/SongDto.java
> +public class SongDto {
Dto의 이름이 명확하지 않습니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +        this.responseLyricList.add(lyricDto);
생성자를 통해 `responseLyricList`를 전달 받는게 아니라 add 함수를 사용하신 이유가 뭔가요?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		List<Music> count = musicRepository.findAllByQWithoutPaging(q, q, q, q, q);
인자를 다 q로 하니까 가독성이 좋지 않네요.
q를 의미에 따라 변수로 분리하는건 어떨까요?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		Pageable page = PageRequest.of(0, 5);
숫자 0과 5가 어떤 의미죠?
숫자 리터럴은 변수로 분리해서 의미를 갖도록 하는게 가독성에 좋습니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
숫자 5가 어떤 의미죠?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSong(String q){
`showSong`이라는 메소드명은 여기서 System.out 을 할 것 같은 느낌을 줍니다.
어떻게 생각하시나요?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		List<Music> count = musicRepository.findAllByQWithoutPaging(q, q, q, q, q);
변수명이 count인게 List 자료형과 어울린다고 생각하시나요?
저는 헷갈립니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
if - else 안에 있는 로직이 이해가 안됩니다.
설명을 적어주세요.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSongAll(String q){
이 메소드는 어떤 상황에서 쓰는 건가요?

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
여기도 if - else 로직이 어떤 작업을하는지 설명을 적어주세요.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseLyric showLyric(String q){
가사 조회가 곡 안에 들어 있는 가사를 조회하는 건가요?
아니면 가사를 가지고 있는 곡을 조회하는 건가요?
메소드 명이 모호합니다.

2023-01-11 07:41 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseLyric showLyricAll(String q){
이 메소드가 위 `showLyric` 메소드랑 어떤 역할의 차이를 가지나요?

2023-01-11 07:44 UTC, yanJuicy requested changes

2023-01-11 07:44 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +package com.hanghaemusic.dto;
여기도 dto 패키지 조정해주세요

2023-01-11 07:44 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    public ResponseArtist(){
이 기본 생성자는 왜 있나요?

2023-01-11 07:44 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    public ResponseArtist(){
개행을 해서 18번 라인과 분리하면 좋을 것 같습니다.

2023-01-11 07:44 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/ArtistService.java
> +        return new ResponseArtist();
검색어와 해당되는 아티스트가 없을 때 빈 아티스트 객체를 리턴하도록 로직을 짜신 이유가 뭔가요?

2023-01-11 07:44 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +public class ResponseLyric {
좋은 것 같아요 ResponseLyricList로 수정하겠습니다

2023-01-11 07:44 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseSong.java
> +public class ResponseSong {
네 수정하겠습니다

2023-01-11 07:50 UTC, yanJuicy requested changes

2023-01-11 07:50 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/controller/MusicApiController.java
> +	public DataResponse showBook(@RequestParam String q){
`showBook`이상하지 않나요?
Book이 왜 나오죠?

2023-01-11 08:00 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +public class ResponseLyric {
네 수정하겠습니다!

2023-01-11 08:11 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	Slice<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like, Pageable pageable);
수정하겠습니다!

2023-01-11 08:18 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	List<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like);
가사로 검색한 결과가 5개 이하일 때 5개를 가져오게 하니까 오류가 나더라고요 그래서 5개 이하일 경우에는 모두 가져오게 처리를 해주려고 2개를 만들었습니다.

2023-01-11 08:20 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +package com.hanghaemusic.dto;
네 수정하겠습니다!

2023-01-11 08:24 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +public class LyricDto {
dto이름 고민해보고 수정하겠습니다!

2023-01-11 08:25 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/LyricDto.java
> +public class LyricDto {
네 수정하겠습니다!

2023-01-11 08:25 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/SongDto.java
> +public class SongDto {
dto이름 고민해보고 수정하겠습니다!

2023-01-11 08:25 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/SongDto.java
> +public class SongDto {
네 수정하겠습니다!

2023-01-11 08:25 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +import com.hanghaemusic.dto.*;
싱글 임포트로 수정하겠습니다!

2023-01-11 08:27 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSong(String q){
그러네요 searchSong으로 수정하겠습니다

2023-01-11 08:37 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		Pageable page = PageRequest.of(0, 5);
곡조회를 할때 더보기 버튼을 누르기 전 5개만 보여지게 하기위해 넣었습니다 수정하겠습니다!

2023-01-11 08:44 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
곡 더보기 버튼을 누르기 전 5개만 보여지게 하기 위해 pageable을 사용하여 5개로 잘랐습니다
근데 곡 검색결과가 5개 이하인 경우에 에러가 발생하였습니다
그래서 곡 검색결과를 count하여 5개 이하인 경우에는 검색결과를 모두 반환,
5개 이상인 경우에는 5개만 반환하기 위해서 if-else를 사용하였습니다!

2023-01-11 08:55 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		List<Music> count = musicRepository.findAllByQWithoutPaging(q, q, q, q, q);
q의미에 따라 변수 분리해보겠습니다! count 변수명은 5개 미만일때와 이상일때 따로 처리를 하기 위해 사용하는데.. totalSongCount가 더 괜찮을까요?

2023-01-11 08:56 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSongAll(String q){
더보기 곡을 미리 작성해보았는데 삭제할까요??

2023-01-11 08:57 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseLyric showLyric(String q){
파라미터 값으로 곡 안에 있는 가사를 조회하는 겁니다! 좀 더 명확하게 수정하겠습니다

2023-01-11 08:59 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
더보기를 하기전 기본적으로 5개만 보여지게 하기 위해 pageable을 이용해 5개로 잘랐는데
가사를 조회결과가 5개 이하면 오류가 발생하였습니다
그래서 조회결과 개수를 세어서 5개 미만이면 전부조회하고
5개 이상이면 5개만 조회하기 위해 if-else를 사용하였습니다

2023-01-11 09:00 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseLyric showLyricAll(String q){
showLyric는 더보기 전 5개만 조회하기 위해 사용하고 showLyricAll은 더보기를 눌렀을때 사용됩니다 괜히 미리 만들어서 헷갈리는 것 같네요 삭제할까요??

2023-01-11 11:04 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +package com.hanghaemusic.dto;
네 수정하겠습니다!

2023-01-11 11:06 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    public ResponseArtist(){
네 수정하겠습니다!

2023-01-11 11:06 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    }
어디 class 말하시는 건가요??

2023-01-11 11:08 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/ArtistService.java
> +        return new ResponseArtist();
값이 null이면 오류가 날 줄 알았는데 테스트 해보니까 잘 작동하네요 수정하겠습니다!

2023-01-11 11:12 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/response/ResponseSearchList.java
> +public class ResponseSearchList {
네 수정하겠습니다!

2023-01-11 11:20 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/response/DataResponse.java
> +public class DataResponse {
CommonResponse 호진님이 만드신건가요??

2023-01-11 11:50 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +        this.responseLyricList.add(lyricDto);
음 Repository에서 받은 Music을 바로 리스트에 넣는 것이 아니라 필요한 정보만 가져와 넣는 과정이 필요했는데 저는 필요한 정보를 LyricDto에 넣고 리스트에 추가 방법으로 생각을 해보았습니다

2023-01-11 11:50 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseLyric.java
> +        this.responseLyricList.add(lyricDto);
리스트에 추가하는

2023-01-11 12:42 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/ArtistService.java
> +        return new ResponseArtist();
다시 확인해보니 artist타입이 Optional이어서 검색 결과가 없으면 No value present 에러가 뜨네요 그래서 따로 처리를 해둔 것 같아요

2023-01-11 12:47 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    public ResponseArtist(){
기본 생성자 ArtistService에서 artist가 null일때 리턴값으로 사용됩니다!

2023-01-11 15:20 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		List<Music> count = musicRepository.findAllByQWithoutPaging(q, q, q, q, q);
count의 뜻이 "무언가의 갯수를 세다"인데 이것이 List 자료형과 어울린다고 생각하시나요?
저는 int나 long 등 숫자를 표현하는 자료형이 어울린다고 생각합니다.

2023-01-11 15:23 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	List<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like);
어떤 메소드가 오류를 발생하나요?

2023-01-11 15:27 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
이거는 Repository의 메소드를 다시 만들어야 할 거 같습니다.
어떤 에러가 발생한다는거죠?

2023-01-11 15:28 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSongAll(String q){
의미가 불분명하네요

2023-01-11 15:30 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
페이징이 5개가 안된다고 오류가 발생하는건 메소드를 잘못 만든 가능성이 큽니다.

2023-01-11 15:38 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/ArtistService.java
> +        return new ResponseArtist();
`Optional의 empty() `함수를 찾아보세요

2023-01-11 15:44 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/response/FindArtistResponse.java
> +    public FindArtistResponse(Optional<Artist> artist){
인자로 왜 Optional을 받나요?

2023-01-11 15:59 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/response/FindArtistResponse.java
> +    public FindArtistResponse(Optional<Artist> artist){
레포지토리에서 가수검색한 값의 타입이 Optional인데, 이 값을 FindArtistResponse에 넣어주고 있어서 Optional로 받습니다!

2023-01-11 17:52 UTC, yanJuicy commented
데이터 응답 형식이 API 문서와 맞지 않습니다.
<img width="510" alt="image" src="https://user-images.githubusercontent.com/43159295/211881044-8426a5fc-fa8a-4b1c-8a6a-bdb48db6ee2a.png">

2023-01-12 02:13 UTC, yanJuicy commented on src/main/java/com/hanghaemusic/service/response/FindArtistResponse.java
> +    public FindArtistResponse(Optional<Artist> artist){
Optional 자체가 null을 가질수도 있다는 의미인데 그러면 인자로 null을 넘겨도 된다는 의미가 되지 않을까요?

2023-01-12 02:24 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/repository/MusicRepository.java
> +	List<Music> findAllByLyricOrdOrderByReleaseDateDesc(@Param("like") String like);
쿼리는 같은데 검색 결과를 모두 가져오냐, 5개를 잘라서 가져오냐의 차이입니다! 
원래 검색 결과를 5개로 잘라서 가져오는 33줄의 메소드만 구현했었는데,
검색 결과가 5개 이하인 경우에는 OufOfIndex 에러가 발생하여서 자르지 않고 전부 가져오기 위해 36번 메소드를 추가하였습니다!

2023-01-12 02:29 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		List<Music> count = musicRepository.findAllByQWithoutPaging(q, q, q, q, q);
그부분을 어제 더 고민해보았는데 저도 어울리지 않다고 생각해서 searchSize로 수정했습니다!

2023-01-12 02:32 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +		if(count.size() < 5){
검색 결과가 5개 이하인 경우에 5개를 자르려고 하니까 OutOfIndex에러가 발생하였습니다 service말고 repository에서 처리하는게 더 괜찮을까요??

2023-01-12 02:33 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/MusicService.java
> +	public ResponseSong showSongAll(String q){
주석을 더 자세하게 수정하겠습니다!

2023-01-12 02:38 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/dto/ResponseArtist.java
> +    public ResponseArtist(Optional<Artist> artist){
ResponseArtist는 레포지토리에서 찾은 데이터에서 가수와 관련된 내용만 가져와 가수 리스트에 넣어 반환해주려고 사용하는데요
레포지토리에서 찾은 데이터 타입이 Optional이어서 인자로 Optional 객체를 받습니다!

2023-01-12 02:39 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/controller/MusicApiController.java
> +	public DataResponse showBook(@RequestParam String q){
네 수정하겠습니다!

2023-01-12 02:43 UTC, yejin0718 commented on src/main/java/com/hanghaemusic/service/response/FindArtistResponse.java
> +    public FindArtistResponse(Optional<Artist> artist){
음 근데 Optional로 안받고 Artist로 받으면 타입이 달라서 에러가 나더라구요

2023-01-12 06:51 UTC, yanJuicy approved these changes

2023-01-12 10:58 UTC, merged