♻️ Refactor : PR시 cd 적용되도록 수정 #5
Challenge02/HangehaeMusicClub-BE pull request #6
Opened 2023-01-04 14:07 UTC by yejin0718

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] PR 제목 규칙
- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정
- [x] PR에는 Projects 탭을 지정하지 않습니다.
- [x] 연결 이슈 close를 작성했는지 확인해주세요!

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
pr시 cd 적용되도록 수정

## 작업사항
- gradle.yml 수정(push시 작동-> pull_request시 작동)

## 변경로직
- 내용을 적어주세요.

## 연결 이슈 close

close #5 

## 스크린샷
HTML 페이지 스크린샷을 첨부해주세요.

## 기타사항
기타사항을 작성해주세요.

2023-01-04 15:12 UTC, yanJuicy requested changes

2023-01-04 15:12 UTC, yanJuicy commented on .github/workflow/ci.yml
> +  AWS_REGION: ap-northeast-2
ci 과정에서 aws 정보들이 필요한가요?

2023-01-05 04:24 UTC, 1Tsw0rd approved these changes

2023-01-05 04:47 UTC, yanJuicy approved these changes

2023-01-05 05:06 UTC, merged